image: fedora:27

stages:
  - test

before_script:
  - dnf install -y python3-flake8 python3-pycodestyle

style:
  stage: test
  script:
    - pycodestyle-3 --ignore=E722,E741,E402,E121,E123,E126,E226,E24,E704 lollypop/*.py
    - flake8 --ignore=E722,E741,E402,E121,E123,E126,E226,E24,E704 lollypop/*.py
