stages:
  - flatpak

variables:
  BUNDLE: "lollypop-git.flatpak"


flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    stage: flatpak
    variables:
        MANIFEST_PATH: "org.gnome.Lollypop.json"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "lollypop"
    script:
        - flatpak-builder app ${MANIFEST_PATH}
        - flatpak build-export repo app
        - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} org.gnome.Lollypop
    artifacts:
        paths:
            - ${BUNDLE}
            - _build/meson-logs/meson-log.txt
        expire_in: 30 days
    cache:
        paths:
             - .flatpak-builder/cache
